### ISSUE TITLE
Clarify which CDI scopes are supported

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-reactive-messaging#14]
For CDI beans that declare a subscriber/publisher/processor.

We should probably also clarify **"when"** the corresponding business methods are invoked.

**Comment by Emily-Jiang** [comment]
`@ApplicationScoped`, `@SessionScoped`, `@ConversationScoped`, `@RequestScoped`, `@Dependent` beans need to be specified when the business methods are invoked.

**Comment by cescoffier** [comment]
Depending on the signature, the method is called:
* the instance is created when the scope is initialized, the method is called immediately after that
* the instance is created when the scope is initialized, the method is called for every item transiting on the streams

This need to be clarified and enforced in the TCK.

**Comment by mkouba** [comment]
`@SessionScoped`, `@ConversationScoped` and `@RequestScoped` do not make sense because an HTTP request needn't be active at the time the method is invoked.

**Comment by hutchig** [comment]
+1 on @mkouba 's  @SessionScoped, @ConversationScoped and @RequestScoped do not make sense because an HTTP request needn't be active at the time the method is invoked."
As it stands....
    I THINK what people are suggesting is that IF there are enough outstanding request(N)
tokens then an incoming request could 'drive' a Publish from an @Outgoing - but if we we do this what will it mean when there is a request incoming and there are no tokens? and what means do we
use to connect up an incoming request to a reactive stream Publisher.
This is not the 'reactive' way and I think @mkouba 's questionw as answered by @cescoffier  without reference to the CDI @Request etc.  based scopes. 

Perhaps a subsequent spec level could tie in JVM/service ingress to reactive streams Publishers based on
feedback from Quarkus experience etc.

**Comment by otaviojava** [comment]
IMHO: Just have one scope already defined such as `@ApplicationScoped`

**Comment by cescoffier** [comment]
With #25 merged, the spec now contains a section about the supported scope.
